### ISSUE TITLE
Don't work.

### ISSUE THREAD

**Issue by useless-g** [NikitaYurasov/ECF#1]
I've tried installing via pip:
INFO: pip is looking at multiple versions of pyecf to determine which version is compatible with other requirements. This could take a while.
Collecting pyecf
  Using cached pyecf-0.0.1-py3-none-any.whl (6.3 kB)
ERROR: Cannot install pyecf==0.0.1 and pyecf==0.0.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    pyecf 0.0.2 depends on setuptools==49.6.0.post20210108
    pyecf 0.0.1 depends on sage==9.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

So, I've tried forking, removing the setuptools from requirements and install manually, but ECF module is empty, and there are no pyecf module.

Then I've tried to use CLI:
/ECF$ python pyecf -n 9671406556917033397649407
python: can't open file 'pyecf': [Errno 2] No such file or directory

/ECF$ python pyecf.py -n 9671406556917033397649407
Factorizing n = 9671406556917033397649407
/home/*/lib/python3.8/site-packages/sympy-1.8-py3.8.egg/sympy/core/mul.py:2023: RuntimeWarning: overflow encountered in double_scalars
  return reduce(operator.mul, a, start)
Traceback (most recent call last):
  File "pyecf.py", line 20, in <module>
    factors = algo.factorize()
  File "/home/*/ECF/lenstas_algo.py", line 153, in factorize
    if self.one_round_factorization(current_factor):
  File "/home/*/ECF/lenstas_algo.py", line 134, in one_round_factorization
    divider = self.find_factor(n)
  File "/home/*//ECF/lenstas_algo.py", line 97, in find_factor
    max_power = int(prod(r_i ** m_i))
OverflowError: cannot convert float infinity to integer

**Comment by NikitaYurasov** [comment]
Hi, @useless-g !

Thank you for your issue. This repo needed some maintenance to make it up to date.

I updated repo. You can follow README to install new version. 
My recommendation is to use `poetry`.
